using System.Globalization;
using System.Security;
using System.Text;

namespace GitHubReadMeStats.Cli;

internal static class SvgRenderer
{
    public static string Render(string viewerLogin, AggregationResult aggregation, int topCount, DateTimeOffset generatedAtUtc)
    {
        IReadOnlyList<AggregatedLanguage> topLanguages = aggregation.Languages.Take(topCount).ToList();

        int width = 640;
        int rowHeight = 38;
        int headerHeight = 100;
        int footerHeight = 54;
        int height = headerHeight + (topLanguages.Count * rowHeight) + footerHeight;

        const int chartX = 32;
        const int chartWidth = 500;

        var sb = new StringBuilder();

        sb.AppendLine($"<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"{width}\" height=\"{height}\" viewBox=\"0 0 {width} {height}\" role=\"img\" aria-label=\"GitHub readme language stats\">");
        sb.AppendLine("  <defs>");
        sb.AppendLine("    <linearGradient id=\"card-bg\" x1=\"0\" x2=\"1\" y1=\"0\" y2=\"1\">");
        sb.AppendLine("      <stop offset=\"0%\" stop-color=\"#0F172A\" />");
        sb.AppendLine("      <stop offset=\"100%\" stop-color=\"#111827\" />");
        sb.AppendLine("    </linearGradient>");
        sb.AppendLine("    <style>");
        sb.AppendLine("      .title { font: 700 24px 'Segoe UI', Arial, sans-serif; fill: #F8FAFC; }");
        sb.AppendLine("      .sub { font: 500 14px 'Segoe UI', Arial, sans-serif; fill: #CBD5E1; }");
        sb.AppendLine("      .label { font: 600 13px 'Segoe UI', Arial, sans-serif; fill: #E2E8F0; }");
        sb.AppendLine("      .value { font: 600 12px 'Segoe UI', Arial, sans-serif; fill: #E2E8F0; }");
        sb.AppendLine("      .muted { font: 500 12px 'Segoe UI', Arial, sans-serif; fill: #94A3B8; }");
        sb.AppendLine("    </style>");
        sb.AppendLine("  </defs>");

        sb.AppendLine($"  <rect x=\"0\" y=\"0\" width=\"{width}\" height=\"{height}\" rx=\"18\" fill=\"url(#card-bg)\" />");
        sb.AppendLine($"  <rect x=\"1\" y=\"1\" width=\"{width - 2}\" height=\"{height - 2}\" rx=\"17\" fill=\"none\" stroke=\"#1E293B\" />");

        sb.AppendLine("  <text x=\"32\" y=\"42\" class=\"title\">GitHub Readme Stats</text>");
        sb.AppendLine($"  <text x=\"32\" y=\"66\" class=\"sub\">@{EscapeXml(viewerLogin)} | {aggregation.IncludedRepositoryCount} repos | updated {generatedAtUtc:yyyy-MM-dd HH:mm} UTC</text>");

        for (int i = 0; i < topLanguages.Count; i++)
        {
            AggregatedLanguage language = topLanguages[i];
            int textY = 98 + (i * rowHeight);
            int barY = textY - 14;

            double barWidth = chartWidth * (language.Percent / 100d);
            if (barWidth > 0 && barWidth < 4)
            {
                barWidth = 4;
            }

            sb.AppendLine($"  <rect x=\"{chartX}\" y=\"{barY}\" width=\"{chartWidth}\" height=\"22\" rx=\"11\" fill=\"#1F2937\" />");
            if (barWidth > 0)
            {
                sb.AppendLine($"  <rect x=\"{chartX}\" y=\"{barY}\" width=\"{barWidth.ToString("0.##", CultureInfo.InvariantCulture)}\" height=\"22\" rx=\"11\" fill=\"{EscapeXml(language.Color)}\" />");
            }

            sb.AppendLine($"  <text x=\"{chartX + 10}\" y=\"{textY + 1}\" class=\"label\">{EscapeXml(language.Name)}</text>");
            sb.AppendLine($"  <text x=\"{chartX + chartWidth - 8}\" y=\"{textY + 1}\" class=\"value\" text-anchor=\"end\">{language.Percent.ToString("0.00", CultureInfo.InvariantCulture)}% ({ToHumanReadableBytes(language.Size)})</text>");
        }

        sb.AppendLine($"  <text x=\"32\" y=\"{height - 20}\" class=\"muted\">Total code size: {ToHumanReadableBytes(aggregation.TotalBytes)} | Generated by {CliParser.ApplicationName}</text>");
        sb.AppendLine("</svg>");

        return sb.ToString();
    }

    public static string ToHumanReadableBytes(long bytes)
    {
        if (bytes < 1024)
        {
            return $"{bytes} B";
        }

        string[] units = new[] { "KB", "MB", "GB", "TB" };
        double value = bytes;
        int unitIndex = -1;

        do
        {
            value /= 1024;
            unitIndex++;
        }
        while (value >= 1024 && unitIndex < units.Length - 1);

        return $"{value.ToString("0.##", CultureInfo.InvariantCulture)} {units[unitIndex]}";
    }

    private static string EscapeXml(string? value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return string.Empty;
        }

        return SecurityElement.Escape(value) ?? string.Empty;
    }
}
